"""Generate the independent Pine v6 POSITION_REVERSAL 10m indicator.

The executable Python oracle owns the canonical numeric/source contract.  This
file imports those constants, renders one deterministic Pine source, and offers
``--check`` byte parity so generated Pine cannot be hand-edited independently.
"""

from __future__ import annotations

import argparse
from hashlib import sha256
from pathlib import Path
import sys

# Direct execution (``python research/generate_...py``) puts ``research/`` rather
# than the repository root on sys.path.  Bootstrap the root before importing the
# canonical oracle so the handoff's direct ``--check`` command is deterministic.
ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from research.phase1_10m_position_reversal_oracle import (
    ALERT_MESSAGES,
    ALERT_TITLES,
    BAR_INTERVAL_MS,
    CANONICAL_CONTRACT_SHA256,
    DAILY_TIMEFRAME,
    DEFAULT_STALE_AFTER_MS,
    EFFECTIVE_NUMBER_SCALE,
    EXPECTED_SYMBOL,
    IDENTITY_ASCII_ALNUM,
    IDENTITY_COMPONENT_MAX_LENGTH,
    IDENTITY_COMPONENT_SAFE_CHARS,
    IDENTITY_ENCODING_VERSION,
    LANE_ID,
    MARKER_TEXTS,
    MAX_REACTION_BARS,
    MINIMUM_SPACE_R,
    MINIMUM_TICK,
    OPPORTUNITY_LIFETIME_BARS,
    PROTOCOL_VERSION,
    REARM_ATR,
    SourceKind,
    STOP_BUFFER_ATR,
)

DEFAULT_OUTPUT = ROOT / "idm_phase1_10m_position_reversal_v1.pine"
CANONICAL_START = f"// POSITION_REVERSAL_10M_CANONICAL_BEGIN {PROTOCOL_VERSION}"
CANONICAL_END = f"// POSITION_REVERSAL_10M_CANONICAL_END {PROTOCOL_VERSION}"

_TEMPLATE = r'''//@version=6
indicator("IDM Phase 1｜10m 位置反转 v1.4", overlay=true)

// Generated by research/generate_phase1_10m_position_reversal_pine_v1.py.
// Do not hand-edit the generated Pine.  This is an indicator with four
// selectable alertconditions only: no order, strategy, webhook, VIX,
// divergence, forming MTF, or lower-timeframe consumer.
__CANONICAL_START__
string PROTOCOL_VERSION = "__PROTOCOL_VERSION__"
string CANONICAL_CONTRACT_SHA256 = "__CONTRACT_SHA256__"
string LANE_ID = "__LANE_ID__"
string EXPECTED_SYMBOL = "__EXPECTED_SYMBOL__"
int BAR_INTERVAL_MS = __BAR_INTERVAL_MS__
int MAX_REACTION_BARS = __MAX_REACTION_BARS__
float MINIMUM_SPACE_R = __MINIMUM_SPACE_R__
float STOP_BUFFER_ATR = __STOP_BUFFER_ATR__
float REARM_ATR = __REARM_ATR__
int OPPORTUNITY_LIFETIME_BARS = __OPPORTUNITY_LIFETIME_BARS__
int DEFAULT_STALE_AFTER_MS = __DEFAULT_STALE_AFTER_MS__
float MINIMUM_TICK = __MINIMUM_TICK__
int EFFECTIVE_NUMBER_SCALE = __EFFECTIVE_NUMBER_SCALE__
string SOURCE_KIND_SATY_ATR_MAP_LEVEL = "__BAND_SOURCE_KIND__"
string SOURCE_KIND_PREVIOUS_COMPLETED_DAILY_ATR = "__ATR_SOURCE_KIND__"
string DAILY_TIMEFRAME = "__DAILY_TIMEFRAME__"
string IDENTITY_ENCODING_VERSION = "__IDENTITY_ENCODING_VERSION__"
int IDENTITY_COMPONENT_MAX_LENGTH = __IDENTITY_COMPONENT_MAX_LENGTH__
string IDENTITY_ASCII_ALNUM = "__IDENTITY_ASCII_ALNUM__"
string IDENTITY_COMPONENT_SAFE_CHARS = "__IDENTITY_COMPONENT_SAFE_CHARS__"

int ROLE_NONE = 0
int ROLE_SUPPORT = 1
int ROLE_RESISTANCE = -1
int ST_WAIT_CLEAR = 0
int ST_APPROACH = 1
int ST_REACTION = 2
int ST_READY = 3
int ST_FAILED = 4
int ST_EXPIRED = 5
int ST_DISABLED = 6
int PLAN_NONE = 0
int PLAN_ACTIVE = 1
int PLAN_INVALIDATED = 2
int PLAN_TARGET_REACHED = 3
int PLAN_EXPIRED = 4
int PLAN_SUPPRESSED = 5
int EV_NONE = 0
int EV_SUPPORT_WATCH = 1
int EV_BOUNCE_CONFIRMED = 2
int EV_RESISTANCE_WATCH = 3
int EV_REJECTION_CONFIRMED = 4
int EV_ACCEPTED_BREAK = 5
int EV_REACTION_EXPIRED = 6
int EV_WAIT_CLEAR_COMPLETED = 7
int EV_POSITION_CONFLICT = 8
int EV_DATA_RESET = 9
int EV_MULTIPLE_SAME_SIDE = 10
int RS_IDLE = 0
int RS_WATCH_ONLY = 1
int RS_READY = 2
int RS_ACCEPTED_BREAK = 3
int RS_TARGET_MISSING = 4
int RS_TARGET_CONSUMED = 5
int RS_RISK_INVALID = 6
int RS_SPACE_LT_1R = 7
int RS_REACTION_EXPIRED = 8
int RS_WAIT_CLEAR_REQUIRED = 9
int RS_WAIT_CLEAR_COMPLETED = 10
int RS_POSITION_CONFLICT = 11
int RS_DATA_RESET = 12
int RS_MULTIPLE_SAME_SIDE = 13
int RS_DATA_DUPLICATE = 14
int RS_DATA_NON_MONOTONIC = 15
int RS_DATA_GAP_RESET = 16
int SURFACE_OK = 0
int SURFACE_SYMBOL = 1
int SURFACE_TIMEFRAME = 2
int SURFACE_NON_STANDARD = 3
int SURFACE_PARAMS = 4
int SURFACE_ATR_DISABLED = 5
int SURFACE_ATR_UNKNOWN = 6
int SURFACE_ATR_EXPIRED = 7
int SURFACE_ATR_CONTRACT = 8
int SURFACE_BAND_DISABLED = 9
int SURFACE_BAND_UNKNOWN = 10
int SURFACE_BAND_EXPIRED = 11
int SURFACE_BAND_CONTRACT = 12
int SURFACE_DUPLICATE_IDENTITY = 13
int SURFACE_BAND_STALE = 14

string ROLE_SUPPORT_TEXT = "SUPPORT"
string ROLE_RESISTANCE_TEXT = "RESISTANCE"
string ROLE_DISABLED_TEXT = "DISABLED"
string STABILITY_PRIOR = "PRIOR_PUBLISHED"
string STABILITY_FORMING = "FORMING"
string STABILITY_UNSTABLE = "UNSTABLE"

bool showReadyHistory = input.bool(true, "显示历史确认标记", group="图面")
bool showWatchHistory = input.bool(false, "显示历史观察标记", group="图面")
bool showFrozenBand = input.bool(true, "显示当前冻结位置区间", group="图面")
bool showCard = input.bool(true, "显示五行状态卡", group="图面")
bool atrEnabled = input.bool(false, "启用上一完成日 ATR", group="上一完成日 ATR")
float atrInput = input.float(98.70936228387525, "ATR 值", minval=0.1, step=0.0001, group="上一完成日 ATR")
string atrSourceKindInput = input.string(SOURCE_KIND_PREVIOUS_COMPLETED_DAILY_ATR, "source_kind", group="上一完成日 ATR")
string atrSourceIdInput = input.string("SATY-ATR-MAP", "source_id", group="上一完成日 ATR")
string atrSourceVersionInput = input.string("2026-07-31-v1", "source_version", group="上一完成日 ATR")
int atrPublishedAtInput = input.time(1785441600000, "published_at", group="上一完成日 ATR")
int atrKnownAtInput = input.time(1785441600000, "known_at", group="上一完成日 ATR")
int atrValidUntilInput = input.time(1785528000000, "valid_until", group="上一完成日 ATR")
string atrSourceTimeframeInput = input.string(DAILY_TIMEFRAME, "source_timeframe", group="上一完成日 ATR")
int atrCompletedSourceOpenInput = input.time(1785384000000, "completed_source_open", group="上一完成日 ATR")
int atrCompletedSourceCloseInput = input.time(1785441600000, "completed_source_close", group="上一完成日 ATR")
string atrStabilityInput = input.string(STABILITY_PRIOR, "stability", options=[STABILITY_PRIOR, STABILITY_FORMING, STABILITY_UNSTABLE], group="上一完成日 ATR")

bool l1Enabled = input.bool(false, "启用", group="具名位 1｜下方触发位")
string l1SourceKind = input.string(SOURCE_KIND_SATY_ATR_MAP_LEVEL, "source_kind", group="具名位 1｜下方触发位")
string l1SourceId = input.string("SATY-ATR-LOWER-TRIGGER", "source_id", group="具名位 1｜下方触发位")
string l1SourceVersion = input.string("v1", "source_version", group="具名位 1｜下方触发位")
string l1RoleText = input.string(ROLE_SUPPORT_TEXT, "role", options=[ROLE_SUPPORT_TEXT, ROLE_RESISTANCE_TEXT, ROLE_DISABLED_TEXT], group="具名位 1｜下方触发位")
float l1Lower = input.float(7421.204590501005, "lower_bound", step=0.0001, group="具名位 1｜下方触发位")
float l1Upper = input.float(7421.204590501005, "upper_bound", step=0.0001, group="具名位 1｜下方触发位")
int l1PublishedAt = input.time(1785441600000, "published_at", group="具名位 1｜下方触发位")
int l1KnownAt = input.time(1785441600000, "level_known_at", group="具名位 1｜下方触发位")
int l1ValidUntil = input.time(1785528000000, "valid_until", group="具名位 1｜下方触发位")
string l1Stability = input.string(STABILITY_PRIOR, "stability", options=[STABILITY_PRIOR, STABILITY_FORMING, STABILITY_UNSTABLE], group="具名位 1｜下方触发位")

bool l2Enabled = input.bool(false, "启用", group="具名位 2｜上方触发位")
string l2SourceKind = input.string(SOURCE_KIND_SATY_ATR_MAP_LEVEL, "source_kind", group="具名位 2｜上方触发位")
string l2SourceId = input.string("SATY-ATR-UPPER-TRIGGER", "source_id", group="具名位 2｜上方触发位")
string l2SourceVersion = input.string("v1", "source_version", group="具名位 2｜上方触发位")
string l2RoleText = input.string(ROLE_RESISTANCE_TEXT, "role", options=[ROLE_SUPPORT_TEXT, ROLE_RESISTANCE_TEXT, ROLE_DISABLED_TEXT], group="具名位 2｜上方触发位")
float l2Lower = input.float(7467.795409498995, "lower_bound", step=0.0001, group="具名位 2｜上方触发位")
float l2Upper = input.float(7467.795409498995, "upper_bound", step=0.0001, group="具名位 2｜上方触发位")
int l2PublishedAt = input.time(1785441600000, "published_at", group="具名位 2｜上方触发位")
int l2KnownAt = input.time(1785441600000, "level_known_at", group="具名位 2｜上方触发位")
int l2ValidUntil = input.time(1785528000000, "valid_until", group="具名位 2｜上方触发位")
string l2Stability = input.string(STABILITY_PRIOR, "stability", options=[STABILITY_PRIOR, STABILITY_FORMING, STABILITY_UNSTABLE], group="具名位 2｜上方触发位")

bool l3Enabled = input.bool(false, "启用", group="具名位 3｜扩展")
string l3SourceKind = input.string(SOURCE_KIND_SATY_ATR_MAP_LEVEL, "source_kind", group="具名位 3｜扩展")
string l3SourceId = input.string("SATY-ATR-LEVEL-3", "source_id", group="具名位 3｜扩展")
string l3SourceVersion = input.string("v1", "source_version", group="具名位 3｜扩展")
string l3RoleText = input.string(ROLE_DISABLED_TEXT, "role", options=[ROLE_SUPPORT_TEXT, ROLE_RESISTANCE_TEXT, ROLE_DISABLED_TEXT], group="具名位 3｜扩展")
float l3Lower = input.float(0.0, "lower_bound", step=0.0001, group="具名位 3｜扩展")
float l3Upper = input.float(0.0, "upper_bound", step=0.0001, group="具名位 3｜扩展")
int l3PublishedAt = input.time(1785441600000, "published_at", group="具名位 3｜扩展")
int l3KnownAt = input.time(1785441600000, "level_known_at", group="具名位 3｜扩展")
int l3ValidUntil = input.time(1785528000000, "valid_until", group="具名位 3｜扩展")
string l3Stability = input.string(STABILITY_PRIOR, "stability", options=[STABILITY_PRIOR, STABILITY_FORMING, STABILITY_UNSTABLE], group="具名位 3｜扩展")

bool l4Enabled = input.bool(false, "启用", group="具名位 4｜扩展")
string l4SourceKind = input.string(SOURCE_KIND_SATY_ATR_MAP_LEVEL, "source_kind", group="具名位 4｜扩展")
string l4SourceId = input.string("SATY-ATR-LEVEL-4", "source_id", group="具名位 4｜扩展")
string l4SourceVersion = input.string("v1", "source_version", group="具名位 4｜扩展")
string l4RoleText = input.string(ROLE_DISABLED_TEXT, "role", options=[ROLE_SUPPORT_TEXT, ROLE_RESISTANCE_TEXT, ROLE_DISABLED_TEXT], group="具名位 4｜扩展")
float l4Lower = input.float(0.0, "lower_bound", step=0.0001, group="具名位 4｜扩展")
float l4Upper = input.float(0.0, "upper_bound", step=0.0001, group="具名位 4｜扩展")
int l4PublishedAt = input.time(1785441600000, "published_at", group="具名位 4｜扩展")
int l4KnownAt = input.time(1785441600000, "level_known_at", group="具名位 4｜扩展")
int l4ValidUntil = input.time(1785528000000, "valid_until", group="具名位 4｜扩展")
string l4Stability = input.string(STABILITY_PRIOR, "stability", options=[STABILITY_PRIOR, STABILITY_FORMING, STABILITY_UNSTABLE], group="具名位 4｜扩展")

f_role_code(string roleText) => roleText == ROLE_SUPPORT_TEXT ? ROLE_SUPPORT : roleText == ROLE_RESISTANCE_TEXT ? ROLE_RESISTANCE : ROLE_NONE
f_identity_component_ok(string value) =>
    int componentLength = str.length(value)
    bool componentOk = componentLength >= 1 and componentLength <= IDENTITY_COMPONENT_MAX_LENGTH and value == str.trim(value)
    if componentOk
        string firstCharacter = str.substring(value, 0, 1)
        string lastCharacter = str.substring(value, componentLength - 1, componentLength)
        componentOk := str.contains(IDENTITY_ASCII_ALNUM, firstCharacter) and str.contains(IDENTITY_ASCII_ALNUM, lastCharacter)
    if componentOk
        for characterIndex = 0 to componentLength - 1
            string character = str.substring(value, characterIndex, characterIndex + 1)
            if not str.contains(IDENTITY_COMPONENT_SAFE_CHARS, character)
                componentOk := false
    componentOk
f_canonical_identity_component(string value) => f_identity_component_ok(value) ? value : ""
f_identity_ok(string sourceId, string sourceVersion) => f_identity_component_ok(sourceId) and f_identity_component_ok(sourceVersion)
f_identity_key(string sourceId, string sourceVersion) => f_identity_ok(sourceId, sourceVersion) ? IDENTITY_ENCODING_VERSION + ":" + sourceId + "@" + sourceVersion : ""
f_band_kind_allowed(string sourceKind) => str.trim(sourceKind) == SOURCE_KIND_SATY_ATR_MAP_LEVEL
f_atr_kind_allowed(string sourceKind) => str.trim(sourceKind) == SOURCE_KIND_PREVIOUS_COMPLETED_DAILY_ATR
f_absolute_window_ok(int publishedAt, int knownAt, int validUntil, int barOpen) => publishedAt > 0 and knownAt > 0 and validUntil > 0 and publishedAt <= barOpen and knownAt <= barOpen and barOpen < validUntil and publishedAt < validUntil and knownAt < validUntil
f_fresh(int publishedAt, int knownAt, int staleMs, int barOpen) => publishedAt > 0 and knownAt > 0 and publishedAt <= barOpen and knownAt <= barOpen and barOpen - math.max(publishedAt, knownAt) <= staleMs
f_delivery_window_ok(int publishedAt, int knownAt, int validUntil, int staleMs, int barOpen, int barClose) => f_absolute_window_ok(publishedAt, knownAt, validUntil, barOpen) and f_fresh(publishedAt, knownAt, staleMs, barOpen) and barClose < validUntil and barClose - math.max(publishedAt, knownAt) <= staleMs
f_band_valid(bool enabled, int role, float lower, float upper, string sourceKind, string sourceId, string sourceVersion, int publishedAt, int knownAt, int validUntil, string stability, int staleMs, int barOpen) => enabled and role != ROLE_NONE and not na(lower) and not na(upper) and lower <= upper and f_band_kind_allowed(sourceKind) and f_identity_ok(sourceId, sourceVersion) and stability == STABILITY_PRIOR and f_absolute_window_ok(publishedAt, knownAt, validUntil, barOpen) and f_fresh(publishedAt, knownAt, staleMs, barOpen)
f_atr_source_bar_ok(string sourceTimeframe, int sourceOpen, int sourceClose, int knownAt, int barOpen) => str.trim(sourceTimeframe) == DAILY_TIMEFRAME and sourceOpen > 0 and sourceClose > sourceOpen and sourceClose <= knownAt and knownAt <= barOpen
f_atr_valid(bool enabled, float atrValue, string sourceKind, string sourceId, string sourceVersion, int publishedAt, int knownAt, int validUntil, string sourceTimeframe, int sourceOpen, int sourceClose, string stability, int staleMs, int barOpen) => enabled and not na(atrValue) and atrValue > 0 and f_atr_kind_allowed(sourceKind) and f_identity_ok(sourceId, sourceVersion) and stability == STABILITY_PRIOR and f_absolute_window_ok(publishedAt, knownAt, validUntil, barOpen) and f_fresh(publishedAt, knownAt, staleMs, barOpen) and f_atr_source_bar_ok(sourceTimeframe, sourceOpen, sourceClose, knownAt, barOpen)
f_scaled(float value) => str.tostring(int(math.round(value * EFFECTIVE_NUMBER_SCALE)))
f_band_effective_key(string sourceKind, string identityKey, int role, float lower, float upper, int publishedAt, int knownAt, int validUntil) => IDENTITY_ENCODING_VERSION + "|B|" + str.trim(sourceKind) + "|" + identityKey + "|" + (role == ROLE_SUPPORT ? ROLE_SUPPORT_TEXT : role == ROLE_RESISTANCE ? ROLE_RESISTANCE_TEXT : ROLE_DISABLED_TEXT) + "|" + f_scaled(lower) + "|" + f_scaled(upper) + "|" + str.tostring(publishedAt) + "|" + str.tostring(knownAt) + "|" + str.tostring(validUntil)
f_atr_effective_key(string sourceKind, string identityKey, float atrValue, int publishedAt, int knownAt, int validUntil, string sourceTimeframe, int sourceOpen, int sourceClose) => IDENTITY_ENCODING_VERSION + "|A|" + str.trim(sourceKind) + "|" + identityKey + "|" + f_scaled(atrValue) + "|" + str.tostring(publishedAt) + "|" + str.tostring(knownAt) + "|" + str.tostring(validUntil) + "|" + str.trim(sourceTimeframe) + "|" + str.tostring(sourceOpen) + "|" + str.tostring(sourceClose)
f_price(float value) => na(value) ? "—" : str.tostring(value, format.mintick)
f_time(int value) => na(value) ? "—" : str.format_time(value, "MM-dd HH:mm", "America/New_York") + " ET"
f_state_text(int state) => state == ST_APPROACH ? "位置观察｜等待收回/压回" : state == ST_READY ? "条件已确认" : state == ST_FAILED ? "本轮不做" : state == ST_EXPIRED ? "反应窗口已到期" : state == ST_DISABLED ? "来源不可用" : "等待位置"
f_reason_text(int reason) => reason == RS_READY ? "空间 ≥ 1R｜条件计划已冻结" : reason == RS_ACCEPTED_BREAK ? "位置已被接受突破｜不倒填" : reason == RS_TARGET_MISSING ? "无开盘前已知的最近反向目标" : reason == RS_TARGET_CONSUMED ? "最近目标已消耗｜不跳远" : reason == RS_RISK_INVALID ? "冻结风险/收益无效" : reason == RS_SPACE_LT_1R ? "最近目标空间 < 1R｜不做" : reason == RS_REACTION_EXPIRED ? "第三根仍无已确认反应" : reason == RS_WAIT_CLEAR_REQUIRED ? "等待完整离位 0.12 ATR" : reason == RS_WAIT_CLEAR_COMPLETED ? "完整离位完成｜下一 K 才可新建" : reason == RS_POSITION_CONFLICT ? "同 K 支撑/阻力冲突｜不做" : reason == RS_MULTIPLE_SAME_SIDE ? "同向多位置同时触及｜不做" : reason == RS_DATA_DUPLICATE ? "重复时间戳｜忽略" : reason == RS_DATA_NON_MONOTONIC ? "时间倒退｜数据重置" : reason == RS_DATA_GAP_RESET ? "10m 断档｜数据重置" : reason == RS_DATA_RESET ? "图表/来源异常｜关闭输出" : reason == RS_WATCH_ONLY ? "仅观察｜不是方向授权" : "等待开盘前已知位置"
f_plan_status_text(int planStatus) => planStatus == PLAN_ACTIVE ? "当前条件计划有效" : planStatus == PLAN_INVALIDATED ? "保护位先到｜计划结束" : planStatus == PLAN_TARGET_REACHED ? "目标先到｜计划结束" : planStatus == PLAN_EXPIRED ? "12 根许可已到期" : planStatus == PLAN_SUPPRESSED ? "数据/来源重置｜计划隐藏" : "无当前计划"
f_surface_reason_text(int surfaceReason) => surfaceReason == SURFACE_SYMBOL ? "配置错误｜仅支持 CAPITALCOM:SPX500" : surfaceReason == SURFACE_TIMEFRAME ? "配置错误｜仅支持原生 10m" : surfaceReason == SURFACE_NON_STANDARD ? "配置错误｜仅支持标准 K 线" : surfaceReason == SURFACE_PARAMS ? "冻结参数合同无效" : surfaceReason == SURFACE_ATR_DISABLED ? "未配置｜先启用上一完成日 ATR" : surfaceReason == SURFACE_ATR_UNKNOWN ? "ATR 来源类型未识别" : surfaceReason == SURFACE_ATR_EXPIRED ? "ATR 已过期｜更新日更来源" : surfaceReason == SURFACE_ATR_CONTRACT ? "ATR 合同无效｜检查时间/身份" : surfaceReason == SURFACE_BAND_DISABLED ? "未配置｜至少启用一个具名位" : surfaceReason == SURFACE_BAND_UNKNOWN ? "具名位来源类型未识别" : surfaceReason == SURFACE_BAND_EXPIRED ? "具名位已过期｜更新日更来源" : surfaceReason == SURFACE_BAND_STALE ? "具名位已超 36 小时｜更新日更来源" : surfaceReason == SURFACE_DUPLICATE_IDENTITY ? "具名位身份重复" : surfaceReason == SURFACE_BAND_CONTRACT ? "具名位合同无效｜检查时间/身份" : "来源可用"
f_plan_gate(int side, float barHigh, float barLow, float episodeHigh, float episodeLow, float atrValue, bool targetPresent, float targetPrice) =>
    float trigger = side == ROLE_SUPPORT ? barHigh : barLow
    float buffer = math.max(2.0 * MINIMUM_TICK, STOP_BUFFER_ATR * atrValue)
    float invalidation = side == ROLE_SUPPORT ? episodeLow - buffer : episodeHigh + buffer
    float risk = side == ROLE_SUPPORT ? trigger - invalidation : invalidation - trigger
    bool targetConsumed = targetPresent and (side == ROLE_SUPPORT ? episodeHigh >= targetPrice : episodeLow <= targetPrice)
    float reward = targetPresent ? (side == ROLE_SUPPORT ? targetPrice - trigger : trigger - targetPrice) : na
    float spaceR = not na(reward) and risk > 0 ? reward / risk : na
    int outState = not targetPresent ? ST_FAILED : targetConsumed ? ST_FAILED : risk <= 0 or na(reward) or reward <= 0 ? ST_FAILED : spaceR < MINIMUM_SPACE_R ? ST_FAILED : ST_READY
    int outReason = not targetPresent ? RS_TARGET_MISSING : targetConsumed ? RS_TARGET_CONSUMED : risk <= 0 or na(reward) or reward <= 0 ? RS_RISK_INVALID : spaceR < MINIMUM_SPACE_R ? RS_SPACE_LT_1R : RS_READY
    [outState, outReason, trigger, invalidation, risk, reward, spaceR]

int staleMs = DEFAULT_STALE_AFTER_MS
bool symbolOk = ticker.standard(syminfo.tickerid) == EXPECTED_SYMBOL
bool timeframeOk = timeframe.period == "10"
bool standardChartOk = chart.is_standard
bool paramsOk = MAX_REACTION_BARS == 3 and MINIMUM_SPACE_R == 1.0 and STOP_BUFFER_ATR == 0.002 and REARM_ATR == 0.12 and OPPORTUNITY_LIFETIME_BARS == 12 and DEFAULT_STALE_AFTER_MS == 129600000 and MINIMUM_TICK == 0.1 and EFFECTIVE_NUMBER_SCALE == 10000000000 and IDENTITY_ENCODING_VERSION == "CID1" and IDENTITY_COMPONENT_MAX_LENGTH == 64
bool hostSurfaceOk = symbolOk and timeframeOk and standardChartOk and paramsOk
bool atrKindOk = f_atr_kind_allowed(atrSourceKindInput)
bool atrExpired = atrEnabled and atrValidUntilInput > 0 and time >= atrValidUntilInput
bool atrValid = f_atr_valid(atrEnabled, atrInput, atrSourceKindInput, atrSourceIdInput, atrSourceVersionInput, atrPublishedAtInput, atrKnownAtInput, atrValidUntilInput, atrSourceTimeframeInput, atrCompletedSourceOpenInput, atrCompletedSourceCloseInput, atrStabilityInput, staleMs, time)
string atrCanonicalSourceId = f_canonical_identity_component(atrSourceIdInput)
string atrCanonicalSourceVersion = f_canonical_identity_component(atrSourceVersionInput)
string atrIdentityKey = f_identity_key(atrSourceIdInput, atrSourceVersionInput)
string atrEffectiveKey = atrValid ? f_atr_effective_key(atrSourceKindInput, atrIdentityKey, atrInput, atrPublishedAtInput, atrKnownAtInput, atrValidUntilInput, atrSourceTimeframeInput, atrCompletedSourceOpenInput, atrCompletedSourceCloseInput) : ""

array<bool> bandEnabled = array.from(l1Enabled, l2Enabled, l3Enabled, l4Enabled)
array<string> bandSourceKind = array.from(l1SourceKind, l2SourceKind, l3SourceKind, l4SourceKind)
array<int> bandRole = array.from(f_role_code(l1RoleText), f_role_code(l2RoleText), f_role_code(l3RoleText), f_role_code(l4RoleText))
array<float> bandLower = array.from(l1Lower, l2Lower, l3Lower, l4Lower)
array<float> bandUpper = array.from(l1Upper, l2Upper, l3Upper, l4Upper)
array<string> bandSourceId = array.from(l1SourceId, l2SourceId, l3SourceId, l4SourceId)
array<string> bandSourceVersion = array.from(l1SourceVersion, l2SourceVersion, l3SourceVersion, l4SourceVersion)
array<int> bandPublishedAt = array.from(l1PublishedAt, l2PublishedAt, l3PublishedAt, l4PublishedAt)
array<int> bandKnownAt = array.from(l1KnownAt, l2KnownAt, l3KnownAt, l4KnownAt)
array<int> bandValidUntil = array.from(l1ValidUntil, l2ValidUntil, l3ValidUntil, l4ValidUntil)
array<string> bandStability = array.from(l1Stability, l2Stability, l3Stability, l4Stability)
array<bool> bandValid = array.new_bool(4, false)
array<string> bandCanonicalSourceId = array.new_string(4, "")
array<string> bandCanonicalSourceVersion = array.new_string(4, "")
array<string> bandIdentityKey = array.new_string(4, "")
array<string> bandEffectiveKey = array.new_string(4, "")
int enabledBandCount = 0
int validBandCount = 0
int earliestBandValidUntil = na
bool anyBandUnknownKind = false
bool anyBandExpired = false
bool anyBandStale = false
bool anyBandInvalidExpiry = false
bool anyBandIdentityInvalid = false
bool anyBandContractInvalid = false
for i = 0 to 3
    bool itemEnabled = array.get(bandEnabled, i)
    string itemKind = array.get(bandSourceKind, i)
    int itemRole = array.get(bandRole, i)
    float itemLower = array.get(bandLower, i)
    float itemUpper = array.get(bandUpper, i)
    string itemSourceId = array.get(bandSourceId, i)
    string itemSourceVersion = array.get(bandSourceVersion, i)
    int itemPublishedAt = array.get(bandPublishedAt, i)
    int itemKnownAt = array.get(bandKnownAt, i)
    int itemValidUntil = array.get(bandValidUntil, i)
    string itemStability = array.get(bandStability, i)
    bool itemKindOk = f_band_kind_allowed(itemKind)
    bool itemIdentityOk = f_identity_ok(itemSourceId, itemSourceVersion)
    bool itemExpired = itemEnabled and itemValidUntil > 0 and time >= itemValidUntil
    bool itemInvalidExpiry = itemEnabled and (itemValidUntil <= 0 or (itemPublishedAt > 0 and itemPublishedAt >= itemValidUntil) or (itemKnownAt > 0 and itemKnownAt >= itemValidUntil))
    bool itemStale = itemEnabled and itemPublishedAt > 0 and itemKnownAt > 0 and itemPublishedAt <= time and itemKnownAt <= time and itemValidUntil > time and time - math.max(itemPublishedAt, itemKnownAt) > staleMs
    bool itemValid = f_band_valid(itemEnabled, itemRole, itemLower, itemUpper, itemKind, itemSourceId, itemSourceVersion, itemPublishedAt, itemKnownAt, itemValidUntil, itemStability, staleMs, time)
    string itemCanonicalSourceId = f_canonical_identity_component(itemSourceId)
    string itemCanonicalSourceVersion = f_canonical_identity_component(itemSourceVersion)
    string itemIdentityKey = f_identity_key(itemSourceId, itemSourceVersion)
    string itemEffectiveKey = itemValid ? f_band_effective_key(itemKind, itemIdentityKey, itemRole, itemLower, itemUpper, itemPublishedAt, itemKnownAt, itemValidUntil) : ""
    array.set(bandValid, i, itemValid)
    array.set(bandCanonicalSourceId, i, itemCanonicalSourceId)
    array.set(bandCanonicalSourceVersion, i, itemCanonicalSourceVersion)
    array.set(bandIdentityKey, i, itemIdentityKey)
    array.set(bandEffectiveKey, i, itemEffectiveKey)
    enabledBandCount += itemEnabled ? 1 : 0
    validBandCount += itemValid ? 1 : 0
    earliestBandValidUntil := itemValid ? (na(earliestBandValidUntil) ? itemValidUntil : math.min(earliestBandValidUntil, itemValidUntil)) : earliestBandValidUntil
    anyBandUnknownKind := anyBandUnknownKind or (itemEnabled and not itemKindOk)
    anyBandExpired := anyBandExpired or itemExpired
    anyBandStale := anyBandStale or itemStale
    anyBandInvalidExpiry := anyBandInvalidExpiry or itemInvalidExpiry
    anyBandIdentityInvalid := anyBandIdentityInvalid or (itemEnabled and not itemIdentityOk)
    anyBandContractInvalid := anyBandContractInvalid or (itemEnabled and itemKindOk and not itemExpired and not itemInvalidExpiry and not itemValid)
bool duplicateIdentityConflict = false
for i = 0 to 3
    if array.get(bandValid, i)
        for j = 0 to 3
            if j > i and array.get(bandValid, j) and array.get(bandIdentityKey, i) == array.get(bandIdentityKey, j)
                duplicateIdentityConflict := true
int sourceSurfaceReason = not symbolOk ? SURFACE_SYMBOL : not timeframeOk ? SURFACE_TIMEFRAME : not standardChartOk ? SURFACE_NON_STANDARD : not paramsOk ? SURFACE_PARAMS : not atrEnabled ? SURFACE_ATR_DISABLED : not atrKindOk ? SURFACE_ATR_UNKNOWN : atrExpired ? SURFACE_ATR_EXPIRED : not atrValid ? SURFACE_ATR_CONTRACT : enabledBandCount == 0 ? SURFACE_BAND_DISABLED : anyBandUnknownKind ? SURFACE_BAND_UNKNOWN : anyBandExpired ? SURFACE_BAND_EXPIRED : anyBandInvalidExpiry ? SURFACE_BAND_CONTRACT : anyBandIdentityInvalid ? SURFACE_BAND_CONTRACT : anyBandStale ? SURFACE_BAND_STALE : duplicateIdentityConflict ? SURFACE_DUPLICATE_IDENTITY : validBandCount == 0 ? SURFACE_BAND_CONTRACT : SURFACE_OK
bool sourceSurfaceOk = sourceSurfaceReason == SURFACE_OK
bool outwardSurfaceOk = sourceSurfaceOk and barstate.isconfirmed

var int st = ST_WAIT_CLEAR
var bool needsClear = false
var int side = ROLE_NONE
var string episodeId = ""
var string episodeSourceKind = ""
var string episodeSourceId = ""
var string episodeSourceVersion = ""
var string episodeSourceIdentityKey = ""
var string episodeSourceEffectiveKey = ""
var int episodePublishedAt = na
var int episodeKnownAt = na
var int episodeValidUntil = na
var float frozenLower = na
var float frozenUpper = na
var float frozenAtr = na
var string frozenAtrSourceKind = ""
var string frozenAtrSourceId = ""
var string frozenAtrSourceVersion = ""
var string frozenAtrIdentityKey = ""
var string frozenAtrEffectiveKey = ""
var int frozenAtrPublishedAt = na
var int frozenAtrKnownAt = na
var int frozenAtrValidUntil = na
var float episodeLow = na
var float episodeHigh = na
var int reactionBarsSeen = 0
var bool watchRegistered = false
var bool terminalRegistered = false
var bool frozenTargetPresent = false
var float frozenTargetPrice = na
var string frozenTargetSourceKind = ""
var string frozenTargetSourceId = ""
var string frozenTargetSourceVersion = ""
var string frozenTargetIdentityKey = ""
var string frozenTargetEffectiveKey = ""
var int frozenTargetPublishedAt = na
var int frozenTargetKnownAt = na
var int frozenTargetValidUntil = na
var int frozenTargetOrder = na
var int lastConfirmedTime = na
var int lastEvent = EV_NONE
var int lastReason = RS_IDLE
var int lastEventTime = na
var float lastMarkerPrice = na
var bool latestPlanPublished = false
var bool latestPlanSuppressed = false
var int latestPlanStatus = PLAN_NONE
var int latestPlanEndTime = na
var string latestOpportunityId = ""
var string latestEpisodeId = ""
var int latestDirection = ROLE_NONE
var float latestTrigger = na
var float latestInvalidation = na
var float latestTarget = na
var string latestTargetSource = ""
var int latestConfirmationTime = na
var int latestVisibleAt = na
var int latestExpiresAt = na
var float latestRisk = na
var float latestReward = na
var float latestSpaceR = na
var string latestSourceEffectiveKey = ""
var string latestTargetEffectiveKey = ""
var string latestAtrEffectiveKey = ""

int ev = EV_NONE
int reason = RS_IDLE
float markerPrice = na
bool sourceContextOk = true
if st == ST_APPROACH
    bool activeSourcePresent = false
    bool activeTargetPresent = not frozenTargetPresent
    for i = 0 to 3
        if array.get(bandValid, i)
            bool sameSource = array.get(bandEffectiveKey, i) == episodeSourceEffectiveKey
            bool sameTarget = frozenTargetPresent and array.get(bandEffectiveKey, i) == frozenTargetEffectiveKey
            activeSourcePresent := activeSourcePresent or sameSource
            activeTargetPresent := activeTargetPresent or sameTarget
    bool activeAtrSame = atrEffectiveKey == frozenAtrEffectiveKey
    sourceContextOk := activeSourcePresent and activeTargetPresent and activeAtrSame

bool latestPlanSourcePresent = false
bool latestPlanTargetPresent = false
if latestPlanStatus == PLAN_ACTIVE
    for i = 0 to 3
        if array.get(bandValid, i)
            latestPlanSourcePresent := latestPlanSourcePresent or array.get(bandEffectiveKey, i) == latestSourceEffectiveKey
            latestPlanTargetPresent := latestPlanTargetPresent or array.get(bandEffectiveKey, i) == latestTargetEffectiveKey
bool latestPlanContextOk = latestPlanStatus != PLAN_ACTIVE or (latestPlanSourcePresent and latestPlanTargetPresent and atrEffectiveKey == latestAtrEffectiveKey)

bool duplicateConfirmed = barstate.isconfirmed and hostSurfaceOk and not na(lastConfirmedTime) and time == lastConfirmedTime
bool backwardReset = barstate.isconfirmed and not na(lastConfirmedTime) and time < lastConfirmedTime
bool gapReset = barstate.isconfirmed and not na(lastConfirmedTime) and time > lastConfirmedTime and time - lastConfirmedTime != BAR_INTERVAL_MS

if barstate.isconfirmed
    if duplicateConfirmed
        reason := RS_DATA_DUPLICATE
    else if not sourceSurfaceOk or backwardReset or gapReset or not sourceContextOk
        if latestPlanStatus == PLAN_ACTIVE
            latestPlanStatus := PLAN_SUPPRESSED
            latestPlanEndTime := time
        st := ST_DISABLED
        needsClear := false
        side := ROLE_NONE
        episodeId := ""
        episodeSourceKind := ""
        episodeSourceId := ""
        episodeSourceVersion := ""
        episodeSourceIdentityKey := ""
        episodeSourceEffectiveKey := ""
        episodePublishedAt := na
        episodeKnownAt := na
        episodeValidUntil := na
        frozenLower := na
        frozenUpper := na
        frozenAtr := na
        frozenAtrSourceKind := ""
        frozenAtrSourceId := ""
        frozenAtrSourceVersion := ""
        frozenAtrIdentityKey := ""
        frozenAtrEffectiveKey := ""
        frozenAtrPublishedAt := na
        frozenAtrKnownAt := na
        frozenAtrValidUntil := na
        episodeLow := na
        episodeHigh := na
        reactionBarsSeen := 0
        watchRegistered := false
        terminalRegistered := false
        frozenTargetPresent := false
        frozenTargetPrice := na
        frozenTargetSourceKind := ""
        frozenTargetSourceId := ""
        frozenTargetSourceVersion := ""
        frozenTargetIdentityKey := ""
        frozenTargetEffectiveKey := ""
        frozenTargetPublishedAt := na
        frozenTargetKnownAt := na
        frozenTargetValidUntil := na
        frozenTargetOrder := na
        latestPlanSuppressed := true
        ev := EV_DATA_RESET
        reason := not hostSurfaceOk ? RS_DATA_RESET : backwardReset ? RS_DATA_NON_MONOTONIC : gapReset ? RS_DATA_GAP_RESET : RS_DATA_RESET
    else
        if latestPlanStatus == PLAN_ACTIVE
            if not latestPlanContextOk
                latestPlanStatus := PLAN_SUPPRESSED
                latestPlanSuppressed := true
                latestPlanEndTime := time
            else if time >= latestExpiresAt
                latestPlanStatus := PLAN_EXPIRED
                latestPlanEndTime := time
            else if time > latestConfirmationTime
                bool planInvalidated = latestDirection == ROLE_SUPPORT ? low <= latestInvalidation : high >= latestInvalidation
                bool planTargetReached = latestDirection == ROLE_SUPPORT ? high >= latestTarget : low <= latestTarget
                if planInvalidated
                    latestPlanStatus := PLAN_INVALIDATED
                    latestPlanEndTime := time_close
                else if planTargetReached
                    latestPlanStatus := PLAN_TARGET_REACHED
                    latestPlanEndTime := time_close
        // A source/gap reset consumes only the reset bar.  On the first later
        // confirmed, contiguous, source-valid bar, restore WAIT_CLEAR and
        // evaluate that same bar instead of discarding one extra eligible K.
        if st == ST_DISABLED
            st := ST_WAIT_CLEAR
            reason := RS_IDLE
        if st == ST_READY or st == ST_FAILED or st == ST_EXPIRED
            st := ST_WAIT_CLEAR
        if needsClear
            float clearDistance = REARM_ATR * frozenAtr
            bool fullClear = side == ROLE_SUPPORT ? low > frozenUpper and close >= frozenUpper + clearDistance : side == ROLE_RESISTANCE ? high < frozenLower and close <= frozenLower - clearDistance : (low > frozenUpper and close >= frozenUpper + clearDistance) or (high < frozenLower and close <= frozenLower - clearDistance)
            if fullClear
                ev := EV_WAIT_CLEAR_COMPLETED
                reason := RS_WAIT_CLEAR_COMPLETED
                needsClear := false
                side := ROLE_NONE
                episodeId := ""
                episodeSourceKind := ""
                episodeSourceId := ""
                episodeSourceVersion := ""
                episodeSourceIdentityKey := ""
                episodeSourceEffectiveKey := ""
                episodePublishedAt := na
                episodeKnownAt := na
                episodeValidUntil := na
                frozenLower := na
                frozenUpper := na
                frozenAtr := na
                frozenAtrSourceKind := ""
                frozenAtrSourceId := ""
                frozenAtrSourceVersion := ""
                frozenAtrIdentityKey := ""
                frozenAtrEffectiveKey := ""
                frozenAtrPublishedAt := na
                frozenAtrKnownAt := na
                frozenAtrValidUntil := na
                episodeLow := na
                episodeHigh := na
                reactionBarsSeen := 0
                watchRegistered := false
                terminalRegistered := false
                frozenTargetPresent := false
                frozenTargetPrice := na
                frozenTargetSourceKind := ""
                frozenTargetSourceId := ""
                frozenTargetSourceVersion := ""
                frozenTargetIdentityKey := ""
                frozenTargetEffectiveKey := ""
                frozenTargetPublishedAt := na
                frozenTargetKnownAt := na
                frozenTargetValidUntil := na
                frozenTargetOrder := na
            else
                reason := RS_WAIT_CLEAR_REQUIRED
        else if st == ST_APPROACH
            reactionBarsSeen += 1
            episodeLow := math.min(episodeLow, low)
            episodeHigh := math.max(episodeHigh, high)
            bool acceptedBreak = side == ROLE_SUPPORT ? close < frozenLower : close > frozenUpper
            bool confirmedReaction = side == ROLE_SUPPORT ? close > frozenUpper : close < frozenLower
            if acceptedBreak
                st := ST_FAILED
                terminalRegistered := true
                needsClear := true
                ev := EV_ACCEPTED_BREAK
                reason := RS_ACCEPTED_BREAK
            else if confirmedReaction
                st := ST_REACTION
                [planState, planReason, trigger, invalidation, risk, reward, spaceR] = f_plan_gate(side, high, low, episodeHigh, episodeLow, frozenAtr, frozenTargetPresent, frozenTargetPrice)
                st := planState
                terminalRegistered := true
                needsClear := true
                ev := side == ROLE_SUPPORT ? EV_BOUNCE_CONFIRMED : EV_REJECTION_CONFIRMED
                reason := planReason
                markerPrice := close
                if planState == ST_READY
                    latestPlanPublished := true
                    latestPlanSuppressed := false
                    latestPlanStatus := PLAN_ACTIVE
                    latestPlanEndTime := na
                    latestOpportunityId := "PR-OP-" + (side == ROLE_SUPPORT ? "L-" : "S-") + episodeSourceIdentityKey + "#" + episodeSourceEffectiveKey + "|" + frozenTargetEffectiveKey + "|" + frozenAtrEffectiveKey + "-" + str.tostring(time)
                    latestEpisodeId := episodeId
                    latestDirection := side
                    latestTrigger := trigger
                    latestInvalidation := invalidation
                    latestTarget := frozenTargetPrice
                    latestTargetSource := frozenTargetIdentityKey
                    latestConfirmationTime := time
                    latestVisibleAt := time_close
                    latestExpiresAt := time_close + OPPORTUNITY_LIFETIME_BARS * BAR_INTERVAL_MS
                    latestRisk := risk
                    latestReward := reward
                    latestSpaceR := spaceR
                    latestSourceEffectiveKey := episodeSourceEffectiveKey
                    latestTargetEffectiveKey := frozenTargetEffectiveKey
                    latestAtrEffectiveKey := frozenAtrEffectiveKey
            else if reactionBarsSeen >= MAX_REACTION_BARS
                st := ST_EXPIRED
                terminalRegistered := true
                needsClear := true
                ev := EV_REACTION_EXPIRED
                reason := RS_REACTION_EXPIRED
            else
                reason := RS_WATCH_ONLY
        else if st == ST_WAIT_CLEAR
            int touchedCount = 0
            int touchedSupportCount = 0
            int touchedResistanceCount = 0
            int touchedIndex = na
            float touchedUnionLower = na
            float touchedUnionUpper = na
            string touchedEffectiveMaterial = ""
            for i = 0 to 3
                if array.get(bandValid, i)
                    int itemRole = array.get(bandRole, i)
                    float itemLower = array.get(bandLower, i)
                    float itemUpper = array.get(bandUpper, i)
                    bool touched = itemRole == ROLE_SUPPORT ? low <= itemUpper : high >= itemLower
                    if touched
                        touchedCount += 1
                        touchedSupportCount += itemRole == ROLE_SUPPORT ? 1 : 0
                        touchedResistanceCount += itemRole == ROLE_RESISTANCE ? 1 : 0
                        touchedIndex := i
                        touchedUnionLower := na(touchedUnionLower) ? itemLower : math.min(touchedUnionLower, itemLower)
                        touchedUnionUpper := na(touchedUnionUpper) ? itemUpper : math.max(touchedUnionUpper, itemUpper)
                        touchedEffectiveMaterial += (str.length(touchedEffectiveMaterial) > 0 ? "|" : "") + array.get(bandEffectiveKey, i)
            if touchedCount > 1
                bool multipleSameSide = touchedSupportCount == 0 or touchedResistanceCount == 0
                side := multipleSameSide ? (touchedSupportCount > 0 ? ROLE_SUPPORT : ROLE_RESISTANCE) : ROLE_NONE
                episodeId := (multipleSameSide ? "PR-MULTIPLE-SAME-SIDE-" : "PR-CONFLICT-") + str.tostring(time) + "#" + touchedEffectiveMaterial + "|" + atrEffectiveKey
                frozenLower := touchedUnionLower
                frozenUpper := touchedUnionUpper
                frozenAtr := atrInput
                frozenAtrSourceKind := atrSourceKindInput
                frozenAtrSourceId := atrCanonicalSourceId
                frozenAtrSourceVersion := atrCanonicalSourceVersion
                frozenAtrIdentityKey := atrIdentityKey
                frozenAtrEffectiveKey := atrEffectiveKey
                frozenAtrPublishedAt := atrPublishedAtInput
                frozenAtrKnownAt := atrKnownAtInput
                frozenAtrValidUntil := atrValidUntilInput
                episodeLow := low
                episodeHigh := high
                terminalRegistered := true
                watchRegistered := false
                st := ST_FAILED
                needsClear := true
                ev := multipleSameSide ? EV_MULTIPLE_SAME_SIDE : EV_POSITION_CONFLICT
                reason := multipleSameSide ? RS_MULTIPLE_SAME_SIDE : RS_POSITION_CONFLICT
            else if touchedCount == 1
                side := array.get(bandRole, touchedIndex)
                episodeSourceKind := array.get(bandSourceKind, touchedIndex)
                episodeSourceId := array.get(bandCanonicalSourceId, touchedIndex)
                episodeSourceVersion := array.get(bandCanonicalSourceVersion, touchedIndex)
                episodeSourceIdentityKey := array.get(bandIdentityKey, touchedIndex)
                episodeSourceEffectiveKey := array.get(bandEffectiveKey, touchedIndex)
                episodePublishedAt := array.get(bandPublishedAt, touchedIndex)
                episodeKnownAt := array.get(bandKnownAt, touchedIndex)
                episodeValidUntil := array.get(bandValidUntil, touchedIndex)
                episodeId := "PR-EP-" + (side == ROLE_SUPPORT ? "L-" : "S-") + episodeSourceIdentityKey + "#" + episodeSourceEffectiveKey + "-" + str.tostring(time)
                frozenLower := array.get(bandLower, touchedIndex)
                frozenUpper := array.get(bandUpper, touchedIndex)
                frozenAtr := atrInput
                frozenAtrSourceKind := atrSourceKindInput
                frozenAtrSourceId := atrCanonicalSourceId
                frozenAtrSourceVersion := atrCanonicalSourceVersion
                frozenAtrIdentityKey := atrIdentityKey
                frozenAtrEffectiveKey := atrEffectiveKey
                frozenAtrPublishedAt := atrPublishedAtInput
                frozenAtrKnownAt := atrKnownAtInput
                frozenAtrValidUntil := atrValidUntilInput
                episodeLow := low
                episodeHigh := high
                reactionBarsSeen := 1
                watchRegistered := true
                terminalRegistered := false
                frozenTargetPresent := false
                frozenTargetPrice := na
                frozenTargetSourceKind := ""
                frozenTargetSourceId := ""
                frozenTargetSourceVersion := ""
                frozenTargetIdentityKey := ""
                frozenTargetEffectiveKey := ""
                frozenTargetPublishedAt := na
                frozenTargetKnownAt := na
                frozenTargetValidUntil := na
                frozenTargetOrder := na
                for i = 0 to 3
                    if array.get(bandValid, i) and array.get(bandRole, i) == -side
                        float candidatePrice = side == ROLE_SUPPORT ? array.get(bandLower, i) : array.get(bandUpper, i)
                        bool ahead = side == ROLE_SUPPORT ? candidatePrice > high : candidatePrice < low
                        bool better = not frozenTargetPresent or (side == ROLE_SUPPORT ? candidatePrice < frozenTargetPrice : candidatePrice > frozenTargetPrice) or (candidatePrice == frozenTargetPrice and i < frozenTargetOrder)
                        if ahead and better
                            frozenTargetPresent := true
                            frozenTargetPrice := candidatePrice
                            frozenTargetSourceKind := array.get(bandSourceKind, i)
                            frozenTargetSourceId := array.get(bandCanonicalSourceId, i)
                            frozenTargetSourceVersion := array.get(bandCanonicalSourceVersion, i)
                            frozenTargetIdentityKey := array.get(bandIdentityKey, i)
                            frozenTargetEffectiveKey := array.get(bandEffectiveKey, i)
                            frozenTargetPublishedAt := array.get(bandPublishedAt, i)
                            frozenTargetKnownAt := array.get(bandKnownAt, i)
                            frozenTargetValidUntil := array.get(bandValidUntil, i)
                            frozenTargetOrder := i
                st := ST_APPROACH
                bool acceptedBreak = side == ROLE_SUPPORT ? close < frozenLower : close > frozenUpper
                bool confirmedReaction = side == ROLE_SUPPORT ? close > frozenUpper : close < frozenLower
                if acceptedBreak
                    st := ST_FAILED
                    terminalRegistered := true
                    needsClear := true
                    ev := EV_ACCEPTED_BREAK
                    reason := RS_ACCEPTED_BREAK
                else if confirmedReaction
                    st := ST_REACTION
                    [planState, planReason, trigger, invalidation, risk, reward, spaceR] = f_plan_gate(side, high, low, episodeHigh, episodeLow, frozenAtr, frozenTargetPresent, frozenTargetPrice)
                    st := planState
                    terminalRegistered := true
                    needsClear := true
                    ev := side == ROLE_SUPPORT ? EV_BOUNCE_CONFIRMED : EV_REJECTION_CONFIRMED
                    reason := planReason
                    markerPrice := close
                    if planState == ST_READY
                        latestPlanPublished := true
                        latestPlanSuppressed := false
                        latestPlanStatus := PLAN_ACTIVE
                        latestPlanEndTime := na
                        latestOpportunityId := "PR-OP-" + (side == ROLE_SUPPORT ? "L-" : "S-") + episodeSourceIdentityKey + "#" + episodeSourceEffectiveKey + "|" + frozenTargetEffectiveKey + "|" + frozenAtrEffectiveKey + "-" + str.tostring(time)
                        latestEpisodeId := episodeId
                        latestDirection := side
                        latestTrigger := trigger
                        latestInvalidation := invalidation
                        latestTarget := frozenTargetPrice
                        latestTargetSource := frozenTargetIdentityKey
                        latestConfirmationTime := time
                        latestVisibleAt := time_close
                        latestExpiresAt := time_close + OPPORTUNITY_LIFETIME_BARS * BAR_INTERVAL_MS
                        latestRisk := risk
                        latestReward := reward
                        latestSpaceR := spaceR
                        latestSourceEffectiveKey := episodeSourceEffectiveKey
                        latestTargetEffectiveKey := frozenTargetEffectiveKey
                        latestAtrEffectiveKey := frozenAtrEffectiveKey
                else
                    ev := side == ROLE_SUPPORT ? EV_SUPPORT_WATCH : EV_RESISTANCE_WATCH
                    reason := RS_WATCH_ONLY
                    markerPrice := side == ROLE_SUPPORT ? low : high
    if ev != EV_NONE
        lastEvent := ev
        lastReason := reason
        lastEventTime := time
        lastMarkerPrice := markerPrice
    if not duplicateConfirmed
        lastConfirmedTime := backwardReset or not hostSurfaceOk ? na : time

bool latestPlanFresh = latestPlanPublished and latestPlanStatus == PLAN_ACTIVE and not latestPlanSuppressed and not na(latestExpiresAt) and time < latestExpiresAt
bool eventSourceIdentityOk = str.length(episodeId) > 0 and str.length(episodeSourceIdentityKey) > 0 and str.length(episodeSourceEffectiveKey) > 0 and episodeSourceKind == SOURCE_KIND_SATY_ATR_MAP_LEVEL
bool eventAtrIdentityOk = str.length(frozenAtrIdentityKey) > 0 and str.length(frozenAtrEffectiveKey) > 0 and frozenAtrSourceKind == SOURCE_KIND_PREVIOUS_COMPLETED_DAILY_ATR
bool eventTargetIdentityOk = frozenTargetPresent and str.length(frozenTargetIdentityKey) > 0 and str.length(frozenTargetEffectiveKey) > 0 and frozenTargetSourceKind == SOURCE_KIND_SATY_ATR_MAP_LEVEL
bool eventSourceDeliveryOk = eventSourceIdentityOk and f_delivery_window_ok(episodePublishedAt, episodeKnownAt, episodeValidUntil, staleMs, time, time_close)
bool eventAtrDeliveryOk = eventAtrIdentityOk and f_delivery_window_ok(frozenAtrPublishedAt, frozenAtrKnownAt, frozenAtrValidUntil, staleMs, time, time_close)
bool eventTargetDeliveryOk = eventTargetIdentityOk and f_delivery_window_ok(frozenTargetPublishedAt, frozenTargetKnownAt, frozenTargetValidUntil, staleMs, time, time_close)
bool readyNumbersOk = not na(latestTrigger) and not na(latestInvalidation) and not na(latestTarget) and not na(latestRisk) and not na(latestReward) and not na(latestSpaceR) and latestRisk > 0 and latestReward > 0 and latestSpaceR >= MINIMUM_SPACE_R
bool readyIdentityOk = latestPlanPublished and latestPlanStatus == PLAN_ACTIVE and str.length(latestOpportunityId) > 0 and latestEpisodeId == episodeId and latestConfirmationTime == time and latestVisibleAt == time_close and latestSourceEffectiveKey == episodeSourceEffectiveKey and latestTargetEffectiveKey == frozenTargetEffectiveKey and latestAtrEffectiveKey == frozenAtrEffectiveKey
bool supportWatchPulse = outwardSurfaceOk and ev == EV_SUPPORT_WATCH and st == ST_APPROACH and reason == RS_WATCH_ONLY and side == ROLE_SUPPORT and watchRegistered and not terminalRegistered and eventSourceDeliveryOk and eventAtrDeliveryOk
bool resistanceWatchPulse = outwardSurfaceOk and ev == EV_RESISTANCE_WATCH and st == ST_APPROACH and reason == RS_WATCH_ONLY and side == ROLE_RESISTANCE and watchRegistered and not terminalRegistered and eventSourceDeliveryOk and eventAtrDeliveryOk
bool longReadyPulse = outwardSurfaceOk and ev == EV_BOUNCE_CONFIRMED and st == ST_READY and reason == RS_READY and side == ROLE_SUPPORT and terminalRegistered and readyIdentityOk and readyNumbersOk and eventSourceDeliveryOk and eventTargetDeliveryOk and eventAtrDeliveryOk
bool shortReadyPulse = outwardSurfaceOk and ev == EV_REJECTION_CONFIRMED and st == ST_READY and reason == RS_READY and side == ROLE_RESISTANCE and terminalRegistered and readyIdentityOk and readyNumbersOk and eventSourceDeliveryOk and eventTargetDeliveryOk and eventAtrDeliveryOk
bool anyOutwardPulse = supportWatchPulse or resistanceWatchPulse or longReadyPulse or shortReadyPulse
bool anyReadyPulse = longReadyPulse or shortReadyPulse
bool currentFrozenBandVisible = showFrozenBand and sourceSurfaceOk and str.length(episodeSourceEffectiveKey) > 0 and not na(frozenLower) and not na(frozenUpper)
color currentBandColor = side == ROLE_SUPPORT ? color.rgb(0, 188, 212) : color.rgb(255, 167, 38)
currentBandLowerPlot = plot(currentFrozenBandVisible ? frozenLower : na, title="当前位置下沿", color=currentBandColor, linewidth=2, style=plot.style_linebr)
currentBandUpperPlot = plot(currentFrozenBandVisible ? frozenUpper : na, title="当前位置上沿", color=currentBandColor, linewidth=2, style=plot.style_linebr)
fill(currentBandLowerPlot, currentBandUpperPlot, title="当前位置区间", color=currentFrozenBandVisible ? color.new(currentBandColor, 86) : na)
plot(anyOutwardPulse ? frozenLower : na, title="PR_BAND_LOWER", display=display.none)
plot(anyOutwardPulse ? frozenUpper : na, title="PR_BAND_UPPER", display=display.none)
plot(anyReadyPulse ? latestTrigger : na, title="PR_TRIGGER", display=display.none)
plot(anyReadyPulse ? latestInvalidation : na, title="PR_INVALIDATION", display=display.none)
plot(anyReadyPulse ? latestTarget : na, title="PR_TARGET", display=display.none)
plot(anyReadyPulse ? latestSpaceR : na, title="PR_SPACE_R", display=display.none)
plotshape((showWatchHistory or barstate.islast) and supportWatchPulse ? markerPrice : na, title="位置反转 支撑观察", text="__MARKER_SUPPORT_WATCH__", style=shape.triangleup, location=location.absolute, color=color.rgb(255, 214, 10), textcolor=color.white, size=size.tiny)
plotshape((showWatchHistory or barstate.islast) and resistanceWatchPulse ? markerPrice : na, title="位置反转 阻力观察", text="__MARKER_RESISTANCE_WATCH__", style=shape.triangledown, location=location.absolute, color=color.rgb(255, 167, 38), textcolor=color.white, size=size.tiny)
plotshape(showReadyHistory and longReadyPulse ? markerPrice : na, title="位置反转 多头确认", text="__MARKER_LONG_READY__", style=shape.labelup, location=location.absolute, color=color.rgb(0, 168, 107), textcolor=color.white, size=size.small)
plotshape(showReadyHistory and shortReadyPulse ? markerPrice : na, title="位置反转 空头确认", text="__MARKER_SHORT_READY__", style=shape.labeldown, location=location.absolute, color=color.rgb(198, 40, 40), textcolor=color.white, size=size.small)

alertcondition(supportWatchPulse, title="__ALERT_TITLE_SUPPORT_WATCH__", message='__ALERT_MESSAGE_SUPPORT_WATCH__')
alertcondition(resistanceWatchPulse, title="__ALERT_TITLE_RESISTANCE_WATCH__", message='__ALERT_MESSAGE_RESISTANCE_WATCH__')
alertcondition(longReadyPulse, title="__ALERT_TITLE_LONG_READY__", message='__ALERT_MESSAGE_LONG_READY__')
alertcondition(shortReadyPulse, title="__ALERT_TITLE_SHORT_READY__", message='__ALERT_MESSAGE_SHORT_READY__')

bool rawWatchEvent = ev == EV_SUPPORT_WATCH or ev == EV_RESISTANCE_WATCH
bool rawReadyEvent = (ev == EV_BOUNCE_CONFIRMED or ev == EV_REJECTION_CONFIRMED) and reason == RS_READY
bool rawNonReadyReaction = (ev == EV_BOUNCE_CONFIRMED or ev == EV_REJECTION_CONFIRMED) and reason != RS_READY
string conclusionText = not sourceSurfaceOk ? f_surface_reason_text(sourceSurfaceReason) : longReadyPulse ? "多头确认｜条件计划" : shortReadyPulse ? "空头确认｜条件计划" : supportWatchPulse ? "支撑观察｜等待站回" : resistanceWatchPulse ? "阻力观察｜等待压回" : rawReadyEvent ? "确认未提醒｜来源在收盘前失效" : rawWatchEvent ? "观察未提醒｜来源在收盘前失效" : rawNonReadyReaction ? "反应成立但不做｜" + f_reason_text(reason) : latestPlanFresh ? f_plan_status_text(latestPlanStatus) : f_state_text(st)
string positionText = str.length(episodeSourceIdentityKey) > 0 ? (side == ROLE_SUPPORT ? "支撑｜" : "阻力｜") + f_price(frozenLower) + "–" + f_price(frozenUpper) : sourceSurfaceOk ? "等待触及｜当前启用 " + str.tostring(validBandCount) + " 个位置" : "未配置/已过期｜见日更来源操作手册"
string validityText = str.length(episodeSourceEffectiveKey) > 0 ? "位置至 " + f_time(episodeValidUntil) + "｜ATR至 " + f_time(frozenAtrValidUntil) : sourceSurfaceOk ? "最早位置至 " + f_time(earliestBandValidUntil) + "｜ATR至 " + f_time(atrValidUntilInput) : "先更新当日位置和上一完成日 ATR"
string protectionText = latestPlanFresh ? "触发 " + f_price(latestTrigger) + "｜保护 " + f_price(latestInvalidation) : st == ST_APPROACH ? (side == ROLE_SUPPORT ? "接受破位 < " + f_price(frozenLower) : "接受突破 > " + f_price(frozenUpper)) : latestPlanPublished ? f_plan_status_text(latestPlanStatus) + (na(latestPlanEndTime) ? "" : "｜" + f_time(latestPlanEndTime)) : "—"
string targetText = latestPlanFresh ? f_price(latestTarget) + "｜空间 " + str.tostring(latestSpaceR, "#.###") + "R" : rawNonReadyReaction or ev == EV_ACCEPTED_BREAK or ev == EV_REACTION_EXPIRED or ev == EV_POSITION_CONFLICT or ev == EV_MULTIPLE_SAME_SIDE or ev == EV_DATA_RESET ? f_reason_text(reason) : not sourceSurfaceOk ? "更新日更来源后重建四个提醒" : f_reason_text(lastReason)
var table card = table.new(position.bottom_right, 2, 5, bgcolor=color.rgb(7, 11, 18), frame_color=color.new(color.white, 35), frame_width=1, border_color=color.new(color.white, 70), border_width=1)
if barstate.islast and showCard
    table.cell(card, 0, 0, "状态", text_color=color.rgb(189, 200, 214), bgcolor=color.rgb(17, 24, 39))
    table.cell(card, 1, 0, conclusionText, text_color=color.white, bgcolor=color.rgb(17, 24, 39))
    table.cell(card, 0, 1, "当前位置", text_color=color.rgb(189, 200, 214))
    table.cell(card, 1, 1, positionText, text_color=color.white)
    table.cell(card, 0, 2, "有效期", text_color=color.rgb(189, 200, 214))
    table.cell(card, 1, 2, validityText, text_color=color.rgb(255, 214, 10))
    table.cell(card, 0, 3, "触发/保护", text_color=color.rgb(189, 200, 214))
    table.cell(card, 1, 3, protectionText, text_color=color.white)
    table.cell(card, 0, 4, "目标/原因", text_color=color.rgb(189, 200, 214))
    table.cell(card, 1, 4, targetText, text_color=color.white)
if barstate.islast and not showCard
    table.clear(card, 0, 0, 1, 4)
__CANONICAL_END__
'''


def render_pine() -> str:
    replacements = {
        "__CANONICAL_START__": CANONICAL_START,
        "__CANONICAL_END__": CANONICAL_END,
        "__PROTOCOL_VERSION__": PROTOCOL_VERSION,
        "__CONTRACT_SHA256__": CANONICAL_CONTRACT_SHA256,
        "__LANE_ID__": LANE_ID,
        "__EXPECTED_SYMBOL__": EXPECTED_SYMBOL,
        "__BAR_INTERVAL_MS__": str(BAR_INTERVAL_MS),
        "__MAX_REACTION_BARS__": str(MAX_REACTION_BARS),
        "__MINIMUM_SPACE_R__": repr(MINIMUM_SPACE_R),
        "__STOP_BUFFER_ATR__": repr(STOP_BUFFER_ATR),
        "__REARM_ATR__": repr(REARM_ATR),
        "__OPPORTUNITY_LIFETIME_BARS__": str(OPPORTUNITY_LIFETIME_BARS),
        "__DEFAULT_STALE_AFTER_MS__": str(DEFAULT_STALE_AFTER_MS),
        "__MINIMUM_TICK__": repr(MINIMUM_TICK),
        "__EFFECTIVE_NUMBER_SCALE__": str(EFFECTIVE_NUMBER_SCALE),
        "__BAND_SOURCE_KIND__": SourceKind.SATY_ATR_MAP_LEVEL.value,
        "__ATR_SOURCE_KIND__": SourceKind.PREVIOUS_COMPLETED_DAILY_ATR.value,
        "__DAILY_TIMEFRAME__": DAILY_TIMEFRAME,
        "__IDENTITY_ENCODING_VERSION__": IDENTITY_ENCODING_VERSION,
        "__IDENTITY_COMPONENT_MAX_LENGTH__": str(IDENTITY_COMPONENT_MAX_LENGTH),
        "__IDENTITY_ASCII_ALNUM__": IDENTITY_ASCII_ALNUM,
        "__IDENTITY_COMPONENT_SAFE_CHARS__": IDENTITY_COMPONENT_SAFE_CHARS,
        "__MARKER_SUPPORT_WATCH__": MARKER_TEXTS[0],
        "__MARKER_LONG_READY__": MARKER_TEXTS[1],
        "__MARKER_RESISTANCE_WATCH__": MARKER_TEXTS[2],
        "__MARKER_SHORT_READY__": MARKER_TEXTS[3],
        "__ALERT_TITLE_SUPPORT_WATCH__": ALERT_TITLES[0],
        "__ALERT_TITLE_RESISTANCE_WATCH__": ALERT_TITLES[1],
        "__ALERT_TITLE_LONG_READY__": ALERT_TITLES[2],
        "__ALERT_TITLE_SHORT_READY__": ALERT_TITLES[3],
        "__ALERT_MESSAGE_SUPPORT_WATCH__": ALERT_MESSAGES[0],
        "__ALERT_MESSAGE_RESISTANCE_WATCH__": ALERT_MESSAGES[1],
        "__ALERT_MESSAGE_LONG_READY__": ALERT_MESSAGES[2],
        "__ALERT_MESSAGE_SHORT_READY__": ALERT_MESSAGES[3],
    }
    source = _TEMPLATE
    for old, new in replacements.items():
        source = source.replace(old, new)
    if "__" in source:
        unresolved = sorted(
            token for token in set(source.split()) if token.startswith("__")
        )
        raise RuntimeError(f"unresolved template tokens: {unresolved}")
    return source.rstrip() + "\n"


PINE_SOURCE = render_pine()
CANONICAL_BLOCK = PINE_SOURCE[
    PINE_SOURCE.index(CANONICAL_START) : PINE_SOURCE.index(CANONICAL_END)
    + len(CANONICAL_END)
]
CANONICAL_BLOCK_SHA256 = sha256(CANONICAL_BLOCK.encode("utf-8")).hexdigest()


def _canonical_slice(start_line: str, end_line: str) -> str:
    """Return an exact line-bounded fragment from the canonical standalone source.

    The global-owner generator consumes these fragments through a token-aware
    namespace adapter.  This keeps the accepted standalone source as the only
    POSITION_REVERSAL producer truth; no generated Pine is regex-patched and the
    standalone render remains byte-identical.
    """

    lines = PINE_SOURCE.splitlines()
    try:
        start = lines.index(start_line)
        end = lines.index(end_line)
    except ValueError as exc:  # pragma: no cover - generator integrity guard
        raise RuntimeError("canonical reversal fragment boundary missing") from exc
    if end < start:
        raise RuntimeError("canonical reversal fragment boundary is reversed")
    return "\n".join(lines[start : end + 1]) + "\n"


def embedded_source_fragments() -> tuple[str, str, str]:
    """Expose exact canonical constants, data inputs, and producer core.

    UI-only inputs, plots, table code and standalone alertconditions are excluded.
    The returned producer core ends at the accepted READY pulse derivation, which
    is the immutable PlanEnvelope handoff boundary used by the 3m global host.
    """

    constants = _canonical_slice(
        f'string PROTOCOL_VERSION = "{PROTOCOL_VERSION}"',
        'string STABILITY_UNSTABLE = "UNSTABLE"',
    )
    data_inputs = _canonical_slice(
        'bool atrEnabled = input.bool(false, "启用上一完成日 ATR", group="上一完成日 ATR")',
        'string l4Stability = input.string(STABILITY_PRIOR, "stability", options=[STABILITY_PRIOR, STABILITY_FORMING, STABILITY_UNSTABLE], group="具名位 4｜扩展")',
    )
    producer_core = _canonical_slice(
        'f_role_code(string roleText) => roleText == ROLE_SUPPORT_TEXT ? ROLE_SUPPORT : roleText == ROLE_RESISTANCE_TEXT ? ROLE_RESISTANCE : ROLE_NONE',
        'bool shortReadyPulse = outwardSurfaceOk and ev == EV_REJECTION_CONFIRMED and st == ST_READY and reason == RS_READY and side == ROLE_RESISTANCE and terminalRegistered and readyIdentityOk and readyNumbersOk and eventSourceDeliveryOk and eventTargetDeliveryOk and eventAtrDeliveryOk',
    )
    return constants, data_inputs, producer_core


def _parse_args(argv: list[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = _parse_args(sys.argv[1:] if argv is None else argv)
    output = args.output
    if args.check:
        if not output.is_file():
            print(f"missing generated Pine: {output}", file=sys.stderr)
            return 1
        actual = output.read_text(encoding="utf-8")
        if actual != PINE_SOURCE:
            print(f"generated Pine byte mismatch: {output}", file=sys.stderr)
            return 1
        print(
            "position-reversal Pine byte parity PASS | "
            f"bytes={len(PINE_SOURCE.encode('utf-8'))} | "
            f"sha256={sha256(PINE_SOURCE.encode('utf-8')).hexdigest()} | "
            f"canonical_sha256={CANONICAL_BLOCK_SHA256}"
        )
        return 0
    output.write_text(PINE_SOURCE, encoding="utf-8")
    print(f"wrote {output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
